create table RILL_WF_TRANSITION_TAKE_TRACE (
    ID_ int(10) not null auto_increment,
    TRANSITION_ID_ varchar(64) not null,
    TRANSITION_NAME_ varchar(255),
    PROC_INST_ID_ varchar(64) not null,
    CREATE_TIME_ timestamp default CURRENT_TIMESTAMP,
    primary key (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

create index RILL_WF_TRANSITION_TAKE_TRACE_PIID on RILL_WF_TRANSITION_TAKE_TRACE(PROC_INST_ID_);

create table RILL_WF_PERSISTENT_CACHE (
    ID_COLUMN VARCHAR(255) not null,
    DATA_COLUMN BINARY(255) not null,
    TIMESTAMP_COLUMN BIGINT(255),
    primary key (ID_COLUMN)
);

drop index ACT_UNIQ_HI_BUS_KEY on ACT_HI_PROCINST;
alter table ACT_RU_IDENTITYLINK drop FOREIGN KEY ACT_FK_TSKASS_TASK;

alter table ACT_RU_EXECUTION drop FOREIGN KEY ACT_FK_EXE_SUPER;
alter table ACT_RU_EXECUTION drop FOREIGN KEY ACT_FK_EXE_PARENT;
alter table ACT_RU_EXECUTION drop FOREIGN KEY ACT_FK_EXE_PROCINST;

alter table ACT_RU_VARIABLE drop FOREIGN KEY ACT_FK_VAR_BYTEARRAY;
alter table ACT_RU_VARIABLE drop FOREIGN KEY ACT_FK_VAR_EXE;
alter table ACT_RU_VARIABLE drop FOREIGN KEY ACT_FK_VAR_PROCINST;

alter table ACT_RU_TASK drop FOREIGN KEY ACT_FK_TASK_PROCDEF;
alter table ACT_RU_TASK drop FOREIGN KEY ACT_FK_TASK_EXE;
alter table ACT_RU_TASK drop FOREIGN KEY ACT_FK_TASK_PROCINST;