// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nu.com.rill.analysis.report.console;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nu.com.rill.analysis.report.console.ReportTemplate;
import nu.com.rill.analysis.report.console.ReportTemplateDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect ReportTemplateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReportTemplateDataOnDemand: @Component;
    
    private Random ReportTemplateDataOnDemand.rnd = new SecureRandom();
    
    private List<ReportTemplate> ReportTemplateDataOnDemand.data;
    
    public ReportTemplate ReportTemplateDataOnDemand.getNewTransientReportTemplate(int index) {
        ReportTemplate obj = new ReportTemplate();
        setBelongToApp(obj, index);
        setContents(obj, index);
        setCreateDate(obj, index);
        setCreator(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ReportTemplateDataOnDemand.setBelongToApp(ReportTemplate obj, int index) {
        String belongToApp = "belongToApp_" + index;
        obj.setBelongToApp(belongToApp);
    }
    
    public void ReportTemplateDataOnDemand.setContents(ReportTemplate obj, int index) {
        byte[] contents = String.valueOf(index).getBytes();
        obj.setContents(contents);
    }
    
    public void ReportTemplateDataOnDemand.setCreateDate(ReportTemplate obj, int index) {
        Date createDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateDate(createDate);
    }
    
    public void ReportTemplateDataOnDemand.setCreator(ReportTemplate obj, int index) {
        String creator = "creator_" + index;
        obj.setCreator(creator);
    }
    
    public void ReportTemplateDataOnDemand.setName(ReportTemplate obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ReportTemplate ReportTemplateDataOnDemand.getSpecificReportTemplate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ReportTemplate obj = data.get(index);
        Long id = obj.getId();
        return ReportTemplate.findReportTemplate(id);
    }
    
    public ReportTemplate ReportTemplateDataOnDemand.getRandomReportTemplate() {
        init();
        ReportTemplate obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ReportTemplate.findReportTemplate(id);
    }
    
    public boolean ReportTemplateDataOnDemand.modifyReportTemplate(ReportTemplate obj) {
        return false;
    }
    
    public void ReportTemplateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ReportTemplate.findReportTemplateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ReportTemplate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ReportTemplate>();
        for (int i = 0; i < 10; i++) {
            ReportTemplate obj = getNewTransientReportTemplate(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
