// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nu.com.rill.analysis.report.console;

import java.util.List;
import nu.com.rill.analysis.report.console.ReportTemplate;
import nu.com.rill.analysis.report.console.ReportTemplateDataOnDemand;
import nu.com.rill.analysis.report.console.ReportTemplateIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReportTemplateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReportTemplateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReportTemplateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReportTemplateIntegrationTest: @Transactional;
    
    @Autowired
    private ReportTemplateDataOnDemand ReportTemplateIntegrationTest.dod;
    
    @Test
    public void ReportTemplateIntegrationTest.testCountReportTemplates() {
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", dod.getRandomReportTemplate());
        long count = ReportTemplate.countReportTemplates();
        Assert.assertTrue("Counter for 'ReportTemplate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testFindReportTemplate() {
        ReportTemplate obj = dod.getRandomReportTemplate();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to provide an identifier", id);
        obj = ReportTemplate.findReportTemplate(id);
        Assert.assertNotNull("Find method for 'ReportTemplate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReportTemplate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testFindAllReportTemplates() {
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", dod.getRandomReportTemplate());
        long count = ReportTemplate.countReportTemplates();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReportTemplate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReportTemplate> result = ReportTemplate.findAllReportTemplates();
        Assert.assertNotNull("Find all method for 'ReportTemplate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReportTemplate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testFindReportTemplateEntries() {
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", dod.getRandomReportTemplate());
        long count = ReportTemplate.countReportTemplates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReportTemplate> result = ReportTemplate.findReportTemplateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReportTemplate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReportTemplate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testFlush() {
        ReportTemplate obj = dod.getRandomReportTemplate();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to provide an identifier", id);
        obj = ReportTemplate.findReportTemplate(id);
        Assert.assertNotNull("Find method for 'ReportTemplate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReportTemplate(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ReportTemplate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testMergeUpdate() {
        ReportTemplate obj = dod.getRandomReportTemplate();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to provide an identifier", id);
        obj = ReportTemplate.findReportTemplate(id);
        boolean modified =  dod.modifyReportTemplate(obj);
        Integer currentVersion = obj.getVersion();
        ReportTemplate merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ReportTemplate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", dod.getRandomReportTemplate());
        ReportTemplate obj = dod.getNewTransientReportTemplate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReportTemplate' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ReportTemplate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReportTemplateIntegrationTest.testRemove() {
        ReportTemplate obj = dod.getRandomReportTemplate();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReportTemplate' failed to provide an identifier", id);
        obj = ReportTemplate.findReportTemplate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ReportTemplate' with identifier '" + id + "'", ReportTemplate.findReportTemplate(id));
    }
    
}
