// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nu.com.rill.analysis.report.console;

import nu.com.rill.analysis.report.console.ReportTemplate;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReportTemplate_Roo_Configurable {
    
    declare @type: ReportTemplate: @Configurable;
    
}
