
package com.baidu.rigel.service.workflow.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RemoteActivitiTemplate", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RemoteActivitiTemplate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.baidu.rigel.service.workflow.ws.client.StringArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskInstanceExtendAttrs", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.GetTaskInstanceExtendAttrs")
    @ResponseWrapper(localName = "getTaskInstanceExtendAttrsResponse", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.GetTaskInstanceExtendAttrsResponse")
    public List<StringArray> getTaskInstanceExtendAttrs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.baidu.rigel.service.workflow.ws.client.RemoteWorkflowResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProcessInstance", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.CreateProcessInstance")
    @ResponseWrapper(localName = "createProcessInstanceResponse", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.CreateProcessInstanceResponse")
    public RemoteWorkflowResponse createProcessInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateProcessInstanceDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.baidu.rigel.service.workflow.ws.client.RemoteWorkflowResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeTaskInstance", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.CompleteTaskInstance")
    @ResponseWrapper(localName = "completeTaskInstanceResponse", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.CompleteTaskInstanceResponse")
    public RemoteWorkflowResponse completeTaskInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        CompleteTaskInstanceDto arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEngineProcessInstanceIdByBOId", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.GetEngineProcessInstanceIdByBOId")
    @ResponseWrapper(localName = "getEngineProcessInstanceIdByBOIdResponse", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", className = "com.baidu.rigel.service.workflow.ws.client.GetEngineProcessInstanceIdByBOIdResponse")
    public String getEngineProcessInstanceIdByBOId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
