
package com.baidu.rigel.service.workflow.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RemoteActivitiTemplateService", targetNamespace = "http://activiti.api.ws.workflow.service.rigel.baidu.com/", wsdlLocation = "http://localhost:8080/rill-bpm-server/BPMWebService?wsdl")
public class RemoteActivitiTemplateService
    extends Service
{

    private final static URL REMOTEACTIVITITEMPLATESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.baidu.rigel.service.workflow.ws.client.RemoteActivitiTemplateService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.baidu.rigel.service.workflow.ws.client.RemoteActivitiTemplateService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/rill-bpm-server/BPMWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/rill-bpm-server/BPMWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REMOTEACTIVITITEMPLATESERVICE_WSDL_LOCATION = url;
    }

    public RemoteActivitiTemplateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteActivitiTemplateService() {
        super(REMOTEACTIVITITEMPLATESERVICE_WSDL_LOCATION, new QName("http://activiti.api.ws.workflow.service.rigel.baidu.com/", "RemoteActivitiTemplateService"));
    }

    /**
     * 
     * @return
     *     returns RemoteActivitiTemplate
     */
    @WebEndpoint(name = "RemoteActivitiTemplatePort")
    public RemoteActivitiTemplate getRemoteActivitiTemplatePort() {
        return super.getPort(new QName("http://activiti.api.ws.workflow.service.rigel.baidu.com/", "RemoteActivitiTemplatePort"), RemoteActivitiTemplate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoteActivitiTemplate
     */
    @WebEndpoint(name = "RemoteActivitiTemplatePort")
    public RemoteActivitiTemplate getRemoteActivitiTemplatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://activiti.api.ws.workflow.service.rigel.baidu.com/", "RemoteActivitiTemplatePort"), RemoteActivitiTemplate.class, features);
    }

}
